services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - zk_data:/bitnami

  kafka:
    image: bitnami/kafka:3.4
    depends_on:
      - zookeeper
    env_file:
      - .env_container
    environment:
      # Point at ZK
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Tweak defaults for production
      - KAFKA_CFG_NUM_PARTITIONS=6
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami

  postgres:
    build:
      context: .
      dockerfile: docker/bronze_pg.Dockerfile 
    image: bronze_pg:latest
    environment:
      - POSTGRES_DB=metadata
      - POSTGRES_USER=meta_user
      - POSTGRES_PASSWORD=meta_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ingest_api:
    build:
      context: .
      dockerfile: docker/ingest_api.Dockerfile 
    image: ingest_api:latest
    env_file:
      - .env_container
    ports:
      - "8000:8000"

  storage_api:
    build:
      context: .
      dockerfile: docker/storage_api.Dockerfile 
    image: storage_api:latest
    env_file:
      - .env_container

  sftp:
    image: atmoz/sftp:latest
    ports:
      - "2222:22"
    volumes:
      #use keys stored in the sftp folder
      - ./sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./sftp/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro
      - ./sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./sftp/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro
      # config defining the users
      - ./sftp/users.conf:/etc/sftp/users.conf:ro
      # uploads directory
      - ./sftp/data:/home

  ingest_sftp:
    build:
      context: .
      dockerfile: docker/ingest_sftp.Dockerfile
    image: ingest_sftp:latest
    env_file:
      - .env_container
    volumes:
      - ./sftp/data:/home:ro

volumes:
  db_data:
  zk_data:
  kafka_data: