services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - zk_data:/bitnami

  kafka:
    image: bitnami/kafka:3.4
    depends_on:
      - zookeeper
    env_file:
      - .env
    environment:
      # Point at ZK
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Tweak defaults for production
      - KAFKA_CFG_NUM_PARTITIONS=6
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami

  postgres:
    build:
      context: .
      dockerfile: docker/bronze_pg.Dockerfile 
    image: bronze_pg:latest
    environment:
      - POSTGRES_DB=metadata
      - POSTGRES_USER=meta_user
      - POSTGRES_PASSWORD=meta_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ingest_api:
    build:
      context: .
      dockerfile: docker/ingest_api.Dockerfile 
    image: ingest_api:latest
    env_file:
      - .env
    ports:
      - "8000:8000"

  storage_api:
    build:
      context: .
      dockerfile: docker/storage_api.Dockerfile 
    image: storage_api:latest
    env_file:
      - .env

  ingest_sftp:
    build:
      context: .
      dockerfile: docker/ingest_sftp.Dockerfile
    image: ingest_sftp:latest
    env_file:
      - .env
    ports:
      - "2222:2222"
    volumes:
      # Persistent storage for uploads with federated directories
      - sftp_uploads:/uploads
      # Mount SSH keys directory - Split into read-only users and writable host keys
      - ./keys/users:/app/keys/users:ro  # User public keys (read-only)
      - sftp_host_keys:/app/keys         # Host keys (writable volume)
    depends_on:
      - kafka
      - postgres

volumes:
  db_data:
  zk_data:
  kafka_data:
  sftp_uploads:
  sftp_host_keys:
